apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hossted-operator.fullname" . }}-controller-manager
  labels:
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
  {{- include "hossted-operator.labels" . | nindent 4 }}
  annotations: {}