customValuesHolder:
  hosstedCustomIngressName:
  - hossted-argocd-server
cve:
  enable: false
env:
  AWS_REGION: us-east-1
  CLOUD_PROVIDER: placeholder
  CONTEXT_NAME: ""
  EMAIL_ID: ""
  HOSSTED_API_URL: https://api.hossted.com/v1/instances
  HOSSTED_ORG_ID: ""
  HOSSTED_TOKEN: ""
  HOSSTED_USER_ID: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MARKET_PLACE: enabled
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""
  PRODUCT_CODE: helloworld
  RECONCILE_DURATION: 10s
helm:
- chartName: argo-cd
  namespace: hossted-argocd
  releaseName: hossted-argocd
  repoName: argo
  repoUrl: https://argoproj.github.io/argo-helm
  values:
  - global.domain=argocd.f.hossted.app
  - configs.params.server\.insecure=true
  - server.ingress.enabled=true
  - server.ingress.hostname=argocd.f.hossted.app
  - server.ingress.ingressClassName=hossted-operator
  - server.ingress.tls=false
  - server.ingress.annotations.nginx\.ingress\.kubernetes\.io/backend-protocol=HTTP
ingress:
  enable: false
logging:
  enable: false
monitoring:
  enable: false
nameOverride: hossted
operator:
  image:
    repository: hossted/operator
    tag: edge
primaryCreds:
  namespace: hossted-argocd
  password:
    key: password
    secretName: argocd-initial-admin-secret
replicas: 1
secret:
  HOSSTED_AUTH_TOKEN: notoken
serviceAccount:
  create: true
  name: hossted-argocd
stop: true
