env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  EMAIL_ID: ""
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: ""
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""
  CLOUD_PROVIDER: "placeholder"
  MARKET_PLACE: "enabled"
  PRODUCT_CODE: "5e3lv67alg3wd65pspyfuunxm"
  AWS_REGION: "us-east-1"
  HOSSTED_TOKEN: ""
  HOSSTED_USER_ID: ""

customValuesHolder: {}
  # hosstedCustomIngressName:
  #   - hossted-argocd-server

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: "notoken"

stop: true

cve:
  enable: false
monitoring:
  enable: false
logging:
  enable: false
ingress:
  enable: false

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge

primaryCreds:
  namespace: "hossted-rabbitmq"
  user: 
    type: "file"
    text: "default_user"
    key: "rabbitmq.conf"
    secretName: "hossted-rabbitmq-config"
  password: 
    key: "rabbitmq-password"
    secretName: "hossted-rabbitmq"

helm:
  - releaseName: "hossted-rabbitmq"
    namespace: "hossted-rabbitmq"
    values: 
      - "ingress.enabled=true"
      - "ingress.hostname=rabbitmq.f.hossted.app"
      - "ingress.ingressClassName=hossted-operator"
      - "auth.username=hossted-admin"
      - "auth.password=hossted-admin-password"
      - "metrics.serviceMonitor.default.enabled=true"
      - "metrics.enabled=true"
    repoName: "rabbitmq"
    chartName: "rabbitmq"
    repoUrl: "https://charts.bitnami.com/bitnami"


serviceAccount:
  create: true          
  name: "hossted-rabbitmq"
