env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  EMAIL_ID: ""
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: ""
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""
  CLOUD_PROVIDER: "azure"
  MARKET_PLACE: "enabled"
  PRODUCT_CODE: "5e3lv67alg3wd65pspyfuunxm"
  AWS_REGION: "us-east-1"
  HOSSTED_TOKEN: ""
  HOSSTED_USER_ID: ""

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: "notoken"

stop: true

cve:
  enable: false
monitoring:
  enable: false
logging:
  enable: false
ingress:
  enable: false

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge

primaryCreds:
  namespace: "hossted-superset"
  user: 
    type: "file"
    text: "--username"
    key: "superset_init.sh"
    secretName: "hossted-superset-config"
  password: 
    type: "file"
    text: "--password"
    key: "superset_init.sh"
    secretName: "hossted-superset-config"

helm:
  - releaseName: "hossted-superset"
    namespace: "hossted-superset"
    values: 
      - "ingress.enabled=true"
      - "ingress.hosts[0]=superset.f.hossted.app"
      - "ingress.ingressClassName=hossted-operator"
      - "init.adminUser.username=hossted-admin"
      - "init.adminUser.password=hossted-admin-password"
      - "extraSecretEnv.SUPERSET_SECRET_KEY=hossted-admin-password"
    repoName: "superset"
    chartName: "superset"
    repoUrl: "http://apache.github.io/superset/"


serviceAccount:
  create: true          
  name: "hossted-superset"
