env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  EMAIL_ID: ""
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: ""
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""
  CLOUD_PROVIDER: "cloud"
  MARKET_PLACE: "enabled"
  PRODUCT_CODE: "5e3lv67alg3wd65pspyfuunxm"
  AWS_REGION: "us-east-1"
  HOSSTED_TOKEN: ""
  HOSSTED_USER_ID: ""


replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: "notoken"

stop: true

cve:
  enable: false
monitoring:
  enable: false
logging:
  enable: false
ingress:
  enable: false

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge

primaryCreds:
  namespace: "hossted-wiki"
  secret: 
    type: "basic-auth"
    name: "wiki-basic-auth"
    value: "hossted-admin:hossted-admin-password"

customValuesHolder: {}

helm:
  - releaseName: "hossted-wiki"
    namespace: "hossted-wiki"
    values: 
      - "ingress.enabled=true"
      - "ingress.hosts[0].host=wiki.f.hossted.app"
      - "ingress.hosts[0].paths[0].path=/"
      - "ingress.hosts[0].paths[0].pathType=Prefix"
      - "ingress.className=hossted-operator"
      - "ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/auth-type=basic"
      - "ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/auth-secret=wiki-basic-auth"
    repoName: "requarks"
    chartName: "wiki"
    repoUrl: "https://charts.js.wiki"

serviceAccount:
  create: true          
  name: "hossted-wiki"
