env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  EMAIL_ID: ""
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: ""
  HOSSTED_TOKEN: ""
  HOSSTED_USER_ID: ""
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""
  CLOUD_PROVIDER: "AWS"
  PRODUCT_CODE: "74gb9tww83ugd3vt68fx24lgv"
  AWS_REGION: "us-east-1"
  MARKET_PLACE: "enabled"

serviceAccount:
  create: false          # Set to true if you want to create a new ServiceAccount
  name: "my-service-account"   # Specify the name of an existing ServiceAccount


replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: "notoken"

stop: true

cve:
  enable: false
monitoring:
  enable: false
logging:
  enable: false
ingress:
  enable: false

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: 0.6.3

primaryCreds:
  namespace: "hossted-metabase"
  secret: 
    type: "basic-auth"
    name: "metabase-basic-auth"
    value: "hossted-admin:hossted-admin-password"

customValuesHolder:
  hosstedCustomIngressName:
    - hossted-argocd-server

helm:
  - releaseName: "hossted-metabase"
    namespace: "hossted-metabase"
    values: 
      - "ingress.enabled=true"
      - "ingress.hosts[0]=metabase.f.hossted.app"
      - "ingress.className=hossted-operator"
      - "ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/auth-type=basic"
      - "ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/auth-secret=metabase-basic-auth"
    repoName: "pmint93"
    chartName: "metabase"
    repoUrl: "https://pmint93.github.io/helm-charts"
