env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  EMAIL_ID: ""
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: ""
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: "notoken"

stop: true

cve:
  enable: false
monitoring:
  enable: false
logging:
  enable: false
ingress:
  enable: false

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge

primaryCreds:
  namespace: "hossted-keycloak"
  user: 
    key: "KEYCLOAK_ADMIN"
    configMap: "hossted-keycloak-env-vars"
  password: 
    key: "admin-password"
    secretName: "hossted-keycloak"
  

helm:
  - releaseName: "hossted-keycloak"
    namespace: "hossted-keycloak"
    values: 
      - "ingress.enabled=true"
      - "ingress.tls=true"
      - "ingress.hostname=keycloak.hossted.com"
      - "ingress.ingressClassName=hossted-operator"
      - "auth.adminPassword=hossted-admin-password"
      - "auth.adminUser=hossted-admin" 
      - "controller.admissionWebhooks.enabled=false"
    repoName: "keycloak"
    chartName: "keycloak"
    repoUrl: "https://charts.bitnami.com/bitnami"
