env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: "123-123-123-123"
  HOSSTED_TOKEN: ""
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""
  CLOUD_PROVIDER: ""
  PRODUCT_CODE: ""
  AWS_REGION: ""
  MARKET_PLACE: ""

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: ""

stop: false

cve:
  enable: true
monitoring:
  enable: true
logging:
  enable: false
ingress:
  enable: true

serviceAccount:
  create: false          # Set to true if you want to create a new ServiceAccount
  name: "my-service-account"   # Specify the name of an existing ServiceAccount

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: 0.6.3

helm:
  - releaseName: "kube-state-metrics"
    namespace: "ksm"
    values:  
      - "selfMonitor.enabled=true"
    repoName: "grafana"
    chartName: "kube-state-metrics"
    repoUrl: "https://prometheus-community.github.io/helm-charts"

primaryCreds: {}
