env:
  HOSSTED_API_URL: "https://api.dev.hossted.com/v1/instances"
  EMAIL_ID: ""
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: ""
  MIMIR_PASSWORD: ""

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: ""

cve:
  enable: true
monitoring:
  enable: true

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
