env:
  HOSSTED_API_URL: "https://api.hossted.com/v1/instances"
  EMAIL_ID: "alex@linnovate.net"
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: "123-123-123-123"
  CONTEXT_NAME: ""
  LOKI_PASSWORD: ""
  LOKI_URL: ""
  LOKI_USERNAME: ""
  MIMIR_PASSWORD: ""
  MIMIR_URL: ""
  MIMIR_USERNAME: ""

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: ""

stop: false

cve:
  enable: true
monitoring:
  enable: true
logging:
  enable: false
ingress:
  enable: true


nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge

helm:
  - releaseName: "kube-state-metrics"
    namespace: "ksm"
    values:  
      - "selfMonitor.enabled=true"
    repoName: "grafana"
    chartName: "kube-state-metrics"
    repoUrl: "https://prometheus-community.github.io/helm-charts"

primaryCreds: {}

