env:
  HOSSTED_API_URL: "https://api.dev.hossted.com/v1/instances"
  EMAIL_ID: "alex@linnovate.net"
  RECONCILE_DURATION: "10s"
  HOSSTED_ORG_ID: "123-123-123-123"
  CONTEXT_NAME: ""

replicas: 1

secret:
  HOSSTED_AUTH_TOKEN: ""

cve:
  enable: true
monitoring:
  enable: true
logging:
  enable: false

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge
