# permissions for end users to view hosstedprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hosstedproject-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: new
    app.kubernetes.io/part-of: new
    app.kubernetes.io/managed-by: kustomize
  name: hosstedproject-viewer-role
rules:
- apiGroups:
  - hossted.com
  resources:
  - hosstedprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hossted.com
  resources:
  - hosstedprojects/status
  verbs:
  - get
