apiVersion: v1
kind: ConfigMap
metadata:
  name: access-object-info
  namespace: hossted-platform
  labels:
    hossted-operator: access-object-info
    helm.sh/chart: hossted-operator-0.5.1
    app.kubernetes.io/name: hossted
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.5.1"
    app.kubernetes.io/managed-by: Helm
data:
  access-object.json: |-
    
    {"namespace":"hossted-keycloak","password":{"key":"admin-password","secretName":"hossted-keycloak"},"user":{"configMap":"hossted-keycloak-env-vars","key":"KEYCLOAK_ADMIN"}}
  