env:
  HOSSTED_API_URL: "https://"
  HOSSTED_AUTH_TOKEN: ""

replicas: 1

nameOverride: hossted

operator:
  image:
    repository: localhost:5001/hossted
    tag: v4
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

