env:
  HOSSTED_API_URL: "https://"
  HOSSTED_AUTH_TOKEN: ""
  EMAIL_ID: ""
replicas: 1

nameOverride: hossted

operator:
  image:
    repository: hossted/operator
    tag: edge
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

