apiVersion: v1
kind: ConfigMap
metadata:
  name: access-object-info
  namespace: {{ .Release.Namespace }}
  labels:
    hossted-operator: access-object-info
    {{- include "hossted-operator.labels" . | nindent 4 }}
data:
  access-object.json: |-
    {{ .Values.primaryCreds | toJson | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-values-holder
  namespace: {{ .Release.Namespace }}
  labels:
    hossted-operator: custom-values-holder
    {{- include "hossted-operator.labels" . | nindent 4 }}
data:
  custom-values.json: |-
    {{ .Values.customValuesHolder | toJson | nindent 4 }}
