apiVersion: hossted.com/v1
kind: Hosstedproject
metadata:
  labels:
    app.kubernetes.io/component: hosstedproject-cr
  {{- include "hossted-operator.labels" . | nindent 4 }}    
  name: {{ include "hossted-operator.fullname" . }}-cr
  annotations:
    "helm.sh/hook": post-install
spec:
  stop: {{ .Values.stop }}
  cve:
    enable: {{ .Values.cve.enable }}
  monitoring:
    enable: {{ .Values.monitoring.enable }}
  logging:
    enable: {{ .Values.logging.enable }}
  ingress:
    enable: {{ .Values.ingress.enable }}    
  helm:
{{- range .Values.helm }}
    - releaseName: "{{ .releaseName }}"
      namespace: "{{ .namespace }}"
      values:  
{{ toYaml .values | indent 8 }}
      repoName: "{{ .repoName }}"
      chartName: "{{ .chartName }}"
      repoUrl: "{{ .repoUrl }}"
{{- end }}
  denyNamespaces:
  - hossted-platform
  - kube-system
  - local-path-storage
  - kube-node-lease
  - kube-public
