apiVersion: v1
kind: Service
metadata:
  name: {{ include "hossted-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    control-plane: controller-manager
  {{- include "hossted-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  {{- include "hossted-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
