apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hossted-operator.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AUTH_TOKEN: {{ .Values.secret.HOSSTED_AUTH_TOKEN | b64enc }}